### ISSUE TITLE
Request for Alternative Access to Pre-trained Models and Dataset Files

### ISSUE THREAD

**Issue by nadiaparsell** [nianfd/IMIR-Net-DSP#1]
Hi,

Thank you for providing the implementation and resources for the IMIR-Net project. I am currently trying to use the pre-trained model and other resources linked in the repository. However, I am facing difficulties downloading these files from Baidu Netdisk due to access issues.

Are there any alternative links (e.g., Google Drive, Dropbox) for the following resources?

Data with Dish Grounding: [Baidu Link](https://pan.baidu.com/s/1VzYF3wWGLrYJHH4liUEhDw?pwd=14x6)
Pre-trained Model on Nutrition5k Dataset: [Baidu Link](https://pan.baidu.com/s/1x-TSXCddzoZjALfB0rIamQ?pwd=hz1e)
Ingredient Feature Extracted from CLIP Text Encoder: [Baidu Link](https://pan.baidu.com/s/159EDLOwMtHj549Cjube0YA?pwd=7f4d)

Any assistance you can provide would be greatly appreciated.

Thank you!

**Comment by nianfd** [comment]
https://drive.google.com/drive/folders/1WRk2exLDBtgfJTx7JiSRUnMzrYnfT_tK?usp=drive_link
---- Replied Message ----
***@***.***>Date8/14/2024 ***@***.***>***@***.***>Subject[nianfd/IMIR-Net-DSP] Request for Alternative Access to Pre-trained Models and Dataset Files (Issue #1)
Hi,
Thank you for providing the implementation and resources for the IMIR-Net project. I am currently trying to use the pre-trained model and other resources linked in the repository. However, I am facing difficulties downloading these files from Baidu Netdisk due to access issues.
Are there any alternative links (e.g., Google Drive, Dropbox) for the following resources?
Data with Dish Grounding: Baidu Link
Pre-trained Model on Nutrition5k Dataset: Baidu Link
Ingredient Feature Extracted from CLIP Text Encoder: Baidu Link
Any assistance you can provide would be greatly appreciated.
Thank you!

**Comment by nadiaparsell** [comment]
Thank you so much for your prompt reply and the links!

Best,

Nadia Parsell
